apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "readsb.fullname" . }}
  labels:
    {{- include "readsb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "readsb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "readsb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "readsb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webservice.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: TZ
              value: {{ .Values.readsb.timezone | quote }}
            - name: READSB_DCFILTER
              value: "true"
            - name: READSB_DEVICE_TYPE
              value: "rtlsdr"
            - name: READSB_FIX
              value: "true"
            - name: READSB_GAIN
              value: "autogain"
            - name: READSB_LAT
              value: {{ .Values.readsb.latitude | quote }}
            - name: READSB_LON
              value: {{ .Values.readsb.longitude | quote }}
            - name: READSB_MODEAC
              value: "true"
            - name: READSB_RX_LOCATION_ACCURACY
              value: "2"
            - name: READSB_STATS_RANGE
              value: "true"
            - name: READSB_NET_ENABLE
              value: "true"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: autogain
              mountPath: /run/autogain
      volumes:
        - name: autogain
          persistentVolumeClaim:
            claimName: {{ include "readsb.fullname" . }}-autogain
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
