apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docker-readsb-protobuf.fullname" . }}-autogain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
