apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-readsb-protobuf.fullname" . }}-web
  labels:
    {{- include "docker-readsb-protobuf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webservice.type }}
  ports:
    - port: {{ .Values.webservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "docker-readsb-protobuf.selectorLabels" . | nindent 4 }}
