apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-adsbexchange.fullname" . }}
  labels:
    {{- include "docker-adsbexchange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 30105
      protocol: TCP
      name: mlat
  selector:
    {{- include "docker-adsbexchange.selectorLabels" . | nindent 4 }}
